import { practiceForTarget } from "@/domain/practices";
import type { Target } from "@/domain/scoring";

import type { EngineChart, EngineRow } from "./schemas";

/**
 * The morning brief (PRD §4.4, §9.9, acceptance #1).
 *
 * A PURE builder, so the one thing the operator reads first every day is fully
 * testable. It is generated by the scheduled job and stored on the thread, so
 * opening the app renders it from Postgres with no model call.
 *
 * Two corrections from the prototype: it hard-coded "8 markets and 5 radars"
 * regardless of what ran, and it said nothing when sweeps failed — §4.1 wants
 * failures stated, with a retry.
 */

export interface MorningBrief {
  text: string;
  chart: EngineChart | null;
  rows: EngineRow[];
  counts: { triggers: number; freshTierOne: number; newToUs: number };
}

/** "Fresh" tier-1 means it landed inside the last fortnight. */
const FRESH_DAYS = 14;
const TOP_DOORS = 6;

export function buildMorningBrief(input: {
  targets: Target[];
  sweepCount: number;
  failed?: string[];
}): MorningBrief {
  const { targets, sweepCount, failed = [] } = input;

  const counts = {
    triggers: targets.length,
    freshTierOne: targets.filter((t) => t.tier === 1 && t.ageDays <= FRESH_DAYS).length,
    newToUs: targets.filter((t) => t.relationship === "new").length,
  };

  const byMarket = new Map<string, number>();
  for (const t of targets) byMarket.set(t.country, (byMarket.get(t.country) ?? 0) + 1);
  const chartData = [...byMarket.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8)
    .map(([name, value]) => ({ name, value }));

  const rows = targets.filter((t) => !t.inPipeline).slice(0, TOP_DOORS).map(toRow);

  const failureNote = failed.length
    ? ` ${failed.length} sweep${failed.length === 1 ? "" : "s"} failed (${failed.join(", ")}) — say "run the sweep again" to retry.`
    : "";

  const text = targets.length
    ? `Morning. Overnight I ran ${sweepCount} sweeps: ${counts.triggers} live trigger${counts.triggers === 1 ? "" : "s"}, ${counts.freshTierOne} fresh tier-one, ${counts.newToUs} new to us. Here is where they landed, and the doors I would open first.${failureNote}`
    : `Morning. ${sweepCount} sweeps ran and it is quiet — nothing new cleared the bar overnight.${failureNote} Worth asking what is moving in a specific market, or who to open first from what we already hold.`;

  return { text, chart: chartData.length ? { type: "bar", title: "Live triggers by market", data: chartData } : null, rows, counts };
}

function toRow(t: Target): EngineRow {
  // practiceForTarget, not practicesForSignal: an AMS door belongs to T2 no
  // matter which signal surfaced it. EngineRow has no tower field, so the
  // practice chosen here is what makeCard routes on.
  const practice = practiceForTarget(t);
  return {
    solution: practice?.name ?? "Organization Transformation",
    company: t.name,
    // Never guessed — the action table shows the role to aim at until a
    // verified person exists (§9.5).
    contact_name: "",
    contact_title: practice?.buyer ?? "CHRO",
    country: t.country,
    industry: t.industry,
    trigger: t.evidence,
    signal: t.signal,
    value: 300_000,
    url: t.url,
  };
}
